// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueyekctaqwzgelghqngd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVleWVrY3RhcXd6Z2VsZ2hxbmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzgxNzEsImV4cCI6MjA2MDIxNDE3MX0.UPYWp5aHZEEfga52xFkzggnChTKepGGPYcheZuEduBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);